### ISSUE TITLE
Not compatible with VS Code '1.80.2'

### ISSUE THREAD

**Issue by neroist** [The-Gamer69/elizas-pride-themes#1]
### Issue
I cannot install the theme on VS Codium 1.80.2. Codium spits out this error:

```
error] Unable to install extension 'elizamuss.elizas-pride-themes' as it is not compatible with VS Code '1.80.2'.
```

**Comment by The-Gamer69** [comment]
I just released a patch for this. Update the extension and it should work. :)

**Comment by neroist** [comment]
It does!! Thank you <3
